language: python

python:
    - "2.7"

env:
    - DJANGO=1.4.2
    - DJANGO=1.5
    - DJANGO=1.6

install:
    - pip install -q django==$DJANGO --use-wheel
    - pip install -q django-nose>=1.2 --use-wheel
    - pip install -q coverage --use-wheel
    - pip install -q -e .

script:
    - python testproj/manage.py test
